export const ALL_COUNTRIES = [
  { code: 'UA', name: 'Україна' },
  { code: 'PL', name: 'Польща' },
  { code: 'DE', name: 'Німеччина' },
  { code: 'CZ', name: 'Чехія' },
  { code: 'LT', name: 'Литва' },
  { code: 'LV', name: 'Латвія' },
  { code: 'EE', name: 'Естонія' },
  { code: 'IT', name: 'Італія' },
  { code: 'ES', name: 'Іспанія' },
  { code: 'SK', name: 'Словаччина' },
  { code: 'HU', name: 'Угорщина' },
  { code: 'RO', name: 'Румунія' },
  { code: 'MD', name: 'Молдова' },
  { code: 'FR', name: 'Франція' },
  { code: 'GB', name: 'Велика Британія' },
  { code: 'AT', name: 'Австрія' },
  { code: 'NL', name: 'Нідерланди' },
];

export const COUNTRY_PHONE: Record<string, { prefix: string; placeholder: string; maxDigits: number }> = {
  UA: { prefix: '+380', placeholder: '(__) ___-__-__', maxDigits: 9 },
  PL: { prefix: '+48',  placeholder: '___ ___ ___',    maxDigits: 9 },
  DE: { prefix: '+49',  placeholder: '___ ________',   maxDigits: 11 },
  CZ: { prefix: '+420', placeholder: '___ ___ ___',    maxDigits: 9 },
  LT: { prefix: '+370', placeholder: '___ _____',      maxDigits: 8 },
  LV: { prefix: '+371', placeholder: '____ ____',      maxDigits: 8 },
  EE: { prefix: '+372', placeholder: '___ ____',       maxDigits: 8 },
  IT: { prefix: '+39',  placeholder: '___ ___ ____',   maxDigits: 10 },
  ES: { prefix: '+34',  placeholder: '___ ___ ___',    maxDigits: 9 },
  SK: { prefix: '+421', placeholder: '___ ___ ___',    maxDigits: 9 },
  HU: { prefix: '+36',  placeholder: '___ ___ ____',   maxDigits: 9 },
  RO: { prefix: '+40',  placeholder: '___ ___ ___',    maxDigits: 9 },
  MD: { prefix: '+373', placeholder: '___ _____',      maxDigits: 8 },
  FR: { prefix: '+33',  placeholder: '_ __ __ __ __',  maxDigits: 9 },
  GB: { prefix: '+44',  placeholder: '____ ______',    maxDigits: 10 },
  AT: { prefix: '+43',  placeholder: '___ _______',    maxDigits: 10 },
  NL: { prefix: '+31',  placeholder: '___ _______',    maxDigits: 9 },
};