export const ALL_COUNTRIES = [
  { code: 'UA', name: 'Україна' },
  { code: 'PL', name: 'Польща' },
  { code: 'DE', name: 'Німеччина' },
  { code: 'CZ', name: 'Чехія' },
  { code: 'LT', name: 'Литва' },
  { code: 'LV', name: 'Латвія' },
  { code: 'EE', name: 'Естонія' },
  { code: 'IT', name: 'Італія' },
  { code: 'ES', name: 'Іспанія' },
  { code: 'SK', name: 'Словаччина' },
  { code: 'HU', name: 'Угорщина' },
  { code: 'RO', name: 'Румунія' },
  { code: 'MD', name: 'Молдова' },
  { code: 'FR', name: 'Франція' },
  { code: 'GB', name: 'Велика Британія' },
  { code: 'AT', name: 'Австрія' },
  { code: 'NL', name: 'Нідерланди' },
];

export const COUNTRY_PHONE: Record<string, { prefix: string; placeholder: string }> = {
  UA: { prefix: '+380', placeholder: '(__) ___-__-__' },
  PL: { prefix: '+48',  placeholder: '___ ___ ___' },
  DE: { prefix: '+49',  placeholder: '___ ________' },
  CZ: { prefix: '+420', placeholder: '___ ___ ___' },
  LT: { prefix: '+370', placeholder: '___ _____' },
  LV: { prefix: '+371', placeholder: '____ ____' },
  EE: { prefix: '+372', placeholder: '___ ____' },
  IT: { prefix: '+39',  placeholder: '___ ___ ____' },
  ES: { prefix: '+34',  placeholder: '___ ___ ___' },
  SK: { prefix: '+421', placeholder: '___ ___ ___' },
  HU: { prefix: '+36',  placeholder: '___ ___ ____' },
  RO: { prefix: '+40',  placeholder: '___ ___ ___' },
  MD: { prefix: '+373', placeholder: '___ _____' },
  FR: { prefix: '+33',  placeholder: '_ __ __ __ __' },
  GB: { prefix: '+44',  placeholder: '____ ______' },
  AT: { prefix: '+43',  placeholder: '___ _______' },
  NL: { prefix: '+31',  placeholder: '___ _______' },
};